### ISSUE TITLE
`holmes ask` does not follow strictly the tsg provided as prompt

### ISSUE THREAD

**Issue by mainred** [robusta-dev/holmesgpt#435]
### What happened?

I created [TSG prompt](https://gist.github.com/mainred/f80bb2284dfcfc878706b0f738027460) as expect the `holmes ask` to follow the TSG to debug the DNS resolution issue in my cluster by
```
holmes ask "detect why the k8s pod client under namespace test-ns cannot resolve dns" -f /home/azureuser/llm/demo/dns_troubleshooting_instructions.md
```

the command stops after several iterations before finding the root case which can be detected if following the TSG.

Besides the TSG as  prompt, I also created a [toolset inspect gadget](https://gist.github.com/mainred/e9e694aa0f4147c042071ffa504c9dd0) to collect DNS trace 

### What did you expect to happen?

`holmes ask` does not follow the TSG to detect the asked error and report how to fix the issue

### How can we reproduce it (as minimally and precisely as possible)?

I tried the command on gpt-40 and gpt-4.5, both failed as described earlier.
```
holmes ask "detect why the k8s pod client under namespace test-ns cannot resolve dns" -f /home/azureuser/llm/demo/dns_troubleshooting_instructions.md
```

**Comment by aantn** [comment]
Hi @mainred, thank you very much for reporting. We're looking into it!
Is there an easy way to reproduce the DNS error on my own cluster to test this?

**Comment by mainred** [comment]
basically I create a network policy to block the dns request from the client pod. the specs can be found here.
```
cat block-dns.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: test-ns
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress: []
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: test-ns
  labels:
    app.kubernetes.io/name: client
spec:
  containers:
  - image: mainred/client:v2
    imagePullPolicy: Always
    name: test-client
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-ns
  labels:
    app.kubernetes.io/name: server
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-ns
spec:
  selector:
    app.kubernetes.io/name: server
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```
