### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'prometheus_url'

### ISSUE THREAD

**Issue by swe1210** [robusta-dev/holmesgpt#581]
### What happened?

Whether setting prometheus_url in ~/.holmes/config.yaml or using environment variables to set PROMETHEUS_URL, an error will be displayed and the prometheus url cannot be set correctly

### What did you expect to happen?

You can set the prometheus url correctly and use prometheus

### How can we reproduce it (as minimally and precisely as possible)?

~/.holmes/config.yaml
```
toolsets:
  prometheus/metrics:
    enabled: true
    config:
      prometheus_url: prometheus_url
```
or 
export PROMETHEUS_URL="prometheus_url"
